export const PORTFOLIO_ACTION = {
  // GET PORTFOLIO
  GET_PORTFOLIO: "PORTFOLIO_ACTION:GET_PORTFOLIO",
  SUCCESS_GET_PORTFOLIO: "PORTFOLIO_ACTION:SUCCESS_GET_PORTFOLIO",
  ERROR_GET_PORTFOLIO: "PORTFOLIO_ACTION:ERROR_GET_PORTFOLIO",
}

export const getPortfolio = () => {
  return { type: PORTFOLIO_ACTION.GET_PORTFOLIO }
}